name: Build

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: false
      - name: Update _config.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1.0.13
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
